Remove Jinja2 Bytecode cache
I'm getting random failures with the scheming extensions

File '/home/adria/dev/pyenvs/ckan/src/ckanext-scheming/ckanext/scheming/templates/scheming/package/read.html', line 3 in top-level template code
  {%- set schema = h.scheming_get_dataset_schema(dataset_type) -%}
File '/home/adria/dev/pyenvs/ckan/local/lib/python2.7/site-packages/jinja2/environment.py', line 434 in getattr
  return obj[attribute]
File '/home/adria/dev/pyenvs/ckan/src/ckan/ckan/lib/helpers.py', line 85 in __getitem__
  key=key
HelperError: Helper 'scheming_get_dataset_schema' has not been defined.

Removing the bytecode cache stops the failures entirely.