Fix symlink in example extension
This was an error introduced in #7677, that was making
`extract_messages` fail:

    python setup.py extract_messages
    running extract_messages
    error: [Errno 2] No such file or directory:
    .../ckan/ckanext/example_theme_docs/v12_extra_public_dir/templates/home/layout.html'