Allow logging config to be at any chained conf file
Not just the last one. Logging config now matches the logic of regular
config options, were higher level ini files will
overwrite lower level ones. Besides the very last ini file of the chain
(the one loaded) doesn't need to contain the logging configuration, so
we no longer this exception:

```
  File "/home/adria/dev/projects/ckan-py310/ckan/ckan/cli/__init__.py", line 158, in load_config
    loggingFileConfig(filename)
  File "/home/adria/.pyenv/versions/3.10.16/lib/python3.10/logging/config.py", line 72, in fileConfig
    formatters = _create_formatters(cp)
  File "/home/adria/.pyenv/versions/3.10.16/lib/python3.10/logging/config.py", line 105, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/home/adria/.pyenv/versions/3.10.16/lib/python3.10/configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```