Fix package_revise test
It started failing when we introduced the requirement for unique
resource ids:

    ckan.logic.ValidationError: None - {'resources': [{'id': ['Resource
        id already exists.']}]}

The reason is clear, two tests were using the same resource on a
`non_clean_db` test class. This was masked in Circle CI because these
two tests were split across containers, but it surfaced when running all
tests sequentially:

https://github.com/ckan/ckan-solr/actions/runs/5463080559/jobs/9943315203